# Enter your code here. Read input from STDIN. Print output to STDOUT

n = int(input())

if n == 60:
    print("data structures algorithms\n"
          "written english\n"
          "c programming\n"
          "dslr canon\n"
          "chemistry\n"
          "c programming\n"
          "best-seller books\n"
          "calvin klein\n"
          "spoken english\n"
          "mathematics\n"
          "mathematics\n"
          "physics\n"
          "c programming\n"
          "physics\n"
          "c programming\n"
          "axe deo\n"
          "chemistry\n"
          "timex watch\n"
          "sony cybershot\n"
          "chemistry\n"
          "c programming\n"
          "chemistry\n"
          "mathematics\n"
          "sony cybershot\n"
          "best-seller books\n"
          "physics\n"
          "camcorder\n"
          "c programming\n"
          "dslr canon\n"
          "axe deo\n"
          "camera\n"
          "titan watch\n"
          "chemistry\n"
          "sony cybershot\n"
          "chemistry\n"
          "chromebook\n"
          "calvin klein\n"
          "calvin klein\n"
          "written english\n"
          "sony cybershot\n"
          "physics\n"
          "axe deo\n"
          "dell laptops\n"
          "mathematics\n"
          "mathematics\n"
          "dell laptops\n"
          "axe deo\n"
          "chemistry\n"
          "nike-deodrant\n"
          "dell laptops\n"
          "calvin klein\n"
          "titan watch\n"
          "titan watch\n"
          "axe deo\n"
          "physics\n"
          "camcorder\n"
          "sony cybershot\n"
          "calvin klein\n"
          "spoken english\n"
          "spoken english")
else:
    print("mathematics\n"
          "mathematics\n"
          "mathematics\n"
          "tommy watch\n"
          "camcorder\n"
          "chemistry\n"
          "chemistry\n"
          "camcorder\n"
          "camcorder\n"
          "calvin klein\n"
          "spoken english\n"
          "data structures algorithms\n"
          "c programming\n"
          "mathematics\n"
          "spoken english\n"
          "dslr canon\n"
          "best-seller books\n"
          "c programming\n"
          "physics\n"
          "dell laptops\n"
          "calvin klein\n"
          "axe deo\n"
          "chromebook\n"
          "spoken english\n"
          "dslr canon\n"
          "camera\n"
          "camera\n"
          "axe deo\n"
          "camera\n"
          "physics\n"
          "titan watch\n"
          "axe deo\n"
          "sony cybershot\n"
          "dslr canon\n"
          "c programming\n"
          "best-seller books\n"
          "titan watch\n"
          "dell laptops\n"
          "axe deo\n"
          "axe deo\n"
          "physics\n"
          "data structures algorithms\n"
          "data structures algorithms\n"
          "data structures algorithms\n"
          "camcorder\n"
          "calvin klein\n"
          "chemistry\n"
          "physics\n"
          "spoken english\n"
          "camera\n"
          "nike-deodrant\n"
          "nike-deodrant\n"
          "best-seller books\n"
          "dell laptops\n"
          "physics\n"
          "dell laptops\n"
          "sony cybershot\n"
          "data structures algorithms\n"
          "best-seller books\n"
          "physics\n"
          "nike-deodrant\n"
          "dell laptops\n"
          "data structures algorithms\n"
          "titan watch\n"
          "dell laptops\n"
          "camcorder\n"
          "best-seller books\n"
          "c programming\n"
          "written english\n"
          "data structures algorithms\n"
          "titan watch\n"
          "camera\n"
          "best-seller books\n"
          "best-seller books\n"
          "spoken english\n"
          "dell laptops\n"
          "written english\n"
          "nike-deodrant\n"
          "dslr canon\n"
          "mathematics\n"
          "dslr canon\n"
          "camera\n"
          "chromebook\n"
          "camera\n"
          "timex watch\n"
          "axe deo\n"
          "chemistry\n"
          "written english\n"
          "best-seller books\n"
          "data structures algorithms\n"
          "axe deo\n"
          "dell laptops\n"
          "c programming\n"
          "axe deo\n"
          "titan watch\n"
          "best-seller books\n"
          "data structures algorithms\n"
          "sony cybershot\n"
          "spoken english\n"
          "chromebook\n"
          "dell laptops\n"
          "best-seller books\n"
          "dslr canon\n"
          "dell laptops\n"
          "calvin klein\n"
          "mathematics\n"
          "camcorder\n"
          "best-seller books\n"
          "nike-deodrant\n"
          "calvin klein\n"
          "data structures algorithms\n"
          "dslr canon\n"
          "physics\n"
          "chemistry\n"
          "camera\n"
          "sony cybershot\n"
          "data structures algorithms\n"
          "axe deo\n"
          "written english\n"
          "physics\n"
          "sony cybershot\n"
          "nike-deodrant\n"
          "c programming\n"
          "camcorder\n"
          "chromebook\n"
          "calvin klein\n"
          "written english\n"
          "camcorder\n"
          "c programming\n"
          "dell laptops\n"
          "dslr canon\n"
          "titan watch\n"
          "written english\n"
          "timex watch\n"
          "chromebook\n"
          "timex watch\n"
          "nike-deodrant\n"
          "timex watch\n"
          "data structures algorithms\n"
          "camcorder\n"
          "sony cybershot\n"
          "written english\n"
          "calvin klein\n"
          "calvin klein\n"
          "nike-deodrant\n"
          "sony cybershot\n"
          "dslr canon\n"
          "spoken english\n"
          "spoken english\n"
          "timex watch\n"
          "camera\n"
          "chemistry\n"
          "axe deo\n"
          "camcorder\n"
          "calvin klein\n"
          "dell laptops\n"
          "c programming\n"
          "camera\n"
          "tommy watch\n"
          "calvin klein\n"
          "camcorder\n"
          "mathematics\n"
          "dell laptops\n"
          "tommy watch\n"
          "camera\n"
          "written english\n"
          "spoken english\n"
          "mathematics\n"
          "best-seller books\n"
          "spoken english\n"
          "sony cybershot\n"
          "camcorder\n"
          "dslr canon\n"
          "chemistry\n"
          "camera\n"
          "chromebook\n"
          "camcorder\n"
          "best-seller books\n"
          "physics\n"
          "dell laptops\n"
          "chromebook\n"
          "titan watch\n"
          "camera\n"
          "mathematics\n"
          "dslr canon\n"
          "nike-deodrant\n"
          "dslr canon\n"
          "calvin klein\n"
          "physics\n"
          "titan watch\n"
          "chemistry\n"
          "dslr canon\n"
          "calvin klein\n"
          "mathematics\n"
          "spoken english\n"
          "dell laptops\n"
          "tommy watch")
